# Site settings
title: 'teocomi | Matteo Cominetti'
shorttitle: teocomi
description: Sometimes I write about code & tech in the AEC industry.<br/>Co-founder of Speckle.<br/>Formerly Arup, Foster+Partners, WeWork, CASE Inc.
url: 'http://teocomi.com'
baseurl: '/'
google_analytics: 'UA-22197648-1'
disqus_shortname: 'teocomi'
name:           'teocomi'
logo:           '/images/profile.png'
locale:         'en_us'

author:
  name: 'Matteo Cominetti'
  email: hello@teocomi.com
  twitter_username: teocomi
  facebook_username: 
  github_username:  teocomi
  linkedin_username:  teocomi

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

plugins: ['jekyll-paginate','jekyll-gist'] 
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']